backend:
  name: github
  repo: edhofdc/rempah-netlify
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth
publish_mode: editorial_workflow
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "products"
    label: "Produk Rempah"
    label_singular: "Produk Rempah"
    folder: "src/content/products"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Nama Produk", name: "title", widget: "string" }
      - { label: "Deskripsi", name: "description", widget: "text" }
      - { label: "Gambar", name: "image", widget: "image", choose_url: true }
      - { label: "Published", name: "published", widget: "boolean", default: true }